bandcamp:
  outputs:
    dev:
      dataset: bandcamp_sale_all_data
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: bandcamp-project-353704
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: bandcamp_sale_prod
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
